---
title: "DataAnalysis"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(tidytext)

knitr::opts_chunk$set(echo = FALSE, fig.width = 12)
if (!exists("inputData"))
  source("sam/data-preprocessing.R")

```

```{r}
inputData$sentences %>% mutate(year2 = paste(year, ifelse(election == "post", "p", ""), sep = "")) %>% ggplot(aes(year2, fill = president)) + geom_bar()
```

```{r}
merged_sentences = bind_rows(inputData$sentences %>% mutate(filter = "Filtered"), inputData$unfiltered_sentences %>% mutate(filter = "Unfiltered"))

merged_sentences %>% mutate(slen = str_length(sentence)) %>% ggplot(aes(x = president, y = slen)) + geom_boxplot() + facet_grid(cols = vars(filter)) + xlab("President") + ylab("Sentence length in characters")
```

```{r}
merged_words = bind_rows(inputData$words %>% mutate(filter = "Filtered"), inputData$unfiltered_words %>% mutate(filter = "Unfiltered"))

merged_words %>% group_by(president, filter, id) %>% summarise(n = n()) %>% select(president, filter, n) %>% ggplot(aes(x = president, y = n)) + geom_boxplot() + facet_grid(cols = vars(filter)) + xlab("President") + ylab("Sentence length in words")
```

```{r eval = FALSE, echo = TRUE}
inputData$sentences %>% mutate(slen = str_length(sentence)) %>% filter(slen > 500) %>% write.table(file = "long_sentences.txt")

inputData$sentences %>% filter(grepl("^\\d{1,2} \\w+ \\d{4}", sentence))
```

