---
title: "Sentiment and Topic Dataframes combined
"
author: "Merve AYDIN"
date: "September 15, 2018"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  library(tidyverse),
  library(tidytext),
  library(stringr),
  library(lubridate),
  library(knitr), 
  library(keras)
)

```
#Load the data
```{r}
load("~/Downloads/dsi-assign2/vanessa/topic_matrix.RData")
load("~/Downloads/dsi-assign2/audrey/sentiment_all.Rdata")
```
###Sentiment and Topic Dataframes combined

```{r}
sentiment_topic_combined = topic_matrix %>% left_join(sentiment_all)
sentiment_topic_combined = sentiment_topic_combined %>% select(-year, -election, -sentence)

set.seed(123)

training_ids <- sentiment_topic_combined %>% 
  group_by(president) %>% 
  sample_frac(0.9) %>% 
  ungroup() %>%
  select(id)

training_sona <- sentiment_topic_combined %>% 
  right_join(training_ids, by = "id") %>%
  select(-id)

test_sona <- sentiment_topic_combined %>% 
  anti_join(training_ids, by = "id") %>%
  select(-id)


# Seperate response variable
dim(sentiment_all) #8068   34
x_train <- as.matrix(training_sona %>% select(-president))
x_test <- as.matrix(test_sona %>% select(-president))


#One-hot encoding for response variable
labels_test = test_sona %>% select(president) %>% unlist()
president_count = labels_test %>% as_tibble() %>% unique() %>% count()
response_tokenizer = text_tokenizer(num_words = president_count+1)
response_tokenizer$fit_on_texts(labels_test)
# Extract response vector, ignoring first (empty) column
y_test = (response_tokenizer$texts_to_matrix(labels_test, mode = "binary"))[,-1]

labels_train = training_sona %>% select(president) %>% unlist()
president_count = labels_train %>% as_tibble() %>% unique() %>% count()
response_tokenizer = text_tokenizer(num_words = president_count + 1)
response_tokenizer$fit_on_texts(labels_train)
# Extract response vector, ignoring first (empty) column
y_train = (response_tokenizer$texts_to_matrix(labels_train, mode = "binary"))[,-1]

model <- keras_model_sequential() #Creating an empty sequential model

#Define a model by sequentially adding layers.

model %>%
  layer_dense(units = 16, activation = 'relu', input_shape = ncol(x_train)) %>%
  layer_dense(units = 16, activation = 'relu', kernel_regularizer = regularizer_l1_l2(l1 = 0.01, l2 = 0.01), bias_initializer = initializer_glorot_normal()) %>%
  layer_dense(units = 6, activation = 'softmax') %>%
  compile(
    loss = 'categorical_crossentropy',
    optimizer = optimizer_rmsprop(lr = 0.003),
    metrics = c('accuracy')
  )

model %>% fit(x_train, y_train, epochs = 10, batch_size = 32 ) %>% plot()

(accuracy_sentiment = (model %>% evaluate(x_test, y_test))$acc)

paste0("Accuracy of sentiment analysis is ", round(accuracy_sentiment,3))
```
Does not calculate the loss for some reason. Cannot include this in the final report.

